image:
  - Visual Studio 2019
      
install:  
  - git clone --depth 1 https://github.com/jarro2783/cxxopts.git

before_build:
- cmd: cmake -H.\cxxopts -G "Visual Studio 16 2019" -A Win32 -B./build_x86 -DCMAKE_INSTALL_PREFIX=./package_x86 -DCXXOPTS_BUILD_EXAMPLES="OFF" -DCXXOPTS_BUILD_TESTS="OFF"
  
build_script:
- cmd: cmake --build build_x86 --target INSTALL --config Release
  
after_test:
  - cmd: nuget pack -Version %APPVEYOR_BUILD_VERSION%
  
artifacts:
  - path: '**\*.nupkg'
  
deploy:
- provider: Environment
  name: production